Update AutomationScriptBuilder.cs
SkylineCommunications/Skyline.DataMiner.CICD.Assemblers pull request #21
Opened 2024-01-16 08:36 UTC by PedroDebevere

2024-01-16 13:39 UTC, MichielOda requested changes

2024-01-16 13:39 UTC, MichielOda commented on Assemblers.Automation/AutomationScriptBuilder.cs
> +
Random empty lines

2024-01-16 13:39 UTC, MichielOda commented on Assemblers.Automation/AutomationScriptBuilder.cs
> +        private static readonly HashSet<string> netFramework481ReferenceAssemblies = new HashSet<string>(new[] { "Accessibility.dll", "CustomMarshalers.dll", "ISymWrapper.dll", "Microsoft.Activities.
Change to titlecasing like field above

2024-01-16 14:54 UTC, PedroDebevere commented on Assemblers.Automation/AutomationScriptBuilder.cs
> +
removed

2024-01-17 07:49 UTC, MichielOda approved these changes

2024-01-17 07:50 UTC, merged